version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: taskqueue-postgres
    environment:
      POSTGRES_DB: task_queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maansi123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: taskqueue-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - REDIS_URL=tcp://taskqueue-redis:6379
      - DB_CONN=host=taskqueue-postgres port=5432 dbname=task_queue user=postgres password=maansi123
    depends_on:
      - postgres
      - redis
    restart: always

  api-server:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - REDIS_URL=tcp://taskqueue-redis:6379
      - DB_CONN=host=taskqueue-postgres port=5432 dbname=task_queue user=postgres password=maansi123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

volumes:
  postgres_data:
  redis_data: